apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: mysql-pv
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
